//
//  CustomDefined.h
//  VPM
//
//  Created by LaiZhaowu on 13-12-6.
//
//

// Setting
#define ENABLED_ROMOTE_NOTIFICATION @"ENABLED_ROMOTE_NOTIFICATION"

// Filter Sidebar
#define FILTER_SIDEBAR_WIDTH 215.0
#define ENABLED_VIEW_DECK_NOTIFICATION @"ENABLED_VIEW_DECK_NOTIFICATION"
#define DISABLED_VIEW_DECK_NOTIFICATION @"DISABLED_VIEW_DECK_NOTIFICATION"
#define TOGGLE_FILTER_SIDEBR_NOTIFICATION @"TOGGLE_FILTER_SIDEBR_NOTIFICATION"
#define FILTER_SIDEBAR_PUSH_SETTING_CHANGED_NOTIFICATION @"FILTER_SIDEBAR_PUSH_SETTING_CHANGED_NOTIFICATION"
#define FILTER_SIDEBAR_PUSH_SETTING_IS_PUSH @"FILTER_SIDEBAR_PUSH_SETTING_IS_PUSH"
#define FILTER_SIDEBAR_FULL_SCREEN_CHANGED_NOTIFICATION @"FILTER_SIDEBAR_FULL_SCREEN_CHANGED_NOTIFICATION"
#define FILTER_SIDEBAR_NORMAL_SCREEN_CHANGED_NOTIFICATION @"FILTER_SIDEBAR_NORMAL_SCREEN_CHANGED_NOTIFICATION"
#define FILTER_SIDEBAR_OPTION_RESETED_NOTIFICATION @"FILTER_SIDEBAR_OPTION_RESETED_NOTIFICATION"
#define PUSH_PRODUCT_NOTIFICATION @"PUSH_PRODUCT_NOTIFICATION"
#define FILTER_SIDEBAR_OPTION_IS_RECOMMEND @"FILTER_SIDEBAR_OPTION_IS_RECOMMEND"
#define FILTER_SIDEBAR_OPTION_PRODUCT_CATEGORY_ID @"FILTER_SIDEBAR_OPTION_PRODUCT_CATEGORY_ID"
#define FILTER_SIDEBAR_OPTION_PRODUCT_BRAND_ID @"FILTER_SIDEBAR_OPTION_PRODUCT_BRAND_ID"
#define FILTER_SIDEBAR_OPTION_PRODUCT_SEARCH_KEYWORD @"FILTER_SIDEBAR_OPTION_PRODUCT_SEARCH_KEYWORD"
#define FILTER_SIDEBAR_OPTION_UPDATED_NOTIFICATION @"FILTER_SIDEBAR_OPTION_UPDATED_NOTIFICATION"
#define PUSH_PRODUCT_SEARCH_NOTIFICATION @"PUSH_PRODUCT_SEARCH_NOTIFICATION"
#define PRODUCT_ID @"PRODUCT_ID"

// Login
#define LOGIN_STATUS_CHANGE_NOTIFICATION @"LOGIN_STATUS_CHANGE_NOTIFICATION"

// Member
#define MEMBER_ID @"MEMBER_ID"
#define LOGIN_USER_NAME @"LOGIN_USER_NAME"
#define LOGIN_PASSWORD @"LOGIN_PASSWORD"

// Temp Order Contestant List
#define TEMP_ORDER_CONTESTANT_LIST @"TEMP_ORDER_CONTESTANT_LIST"
